FROM node:14.15.0

WORKDIR /app
COPY package.json ./
RUN npm install
COPY ./tsconfig.json ./
COPY ./@types ./@types
COPY src /app/src
RUN npm run build
RUN npm prune --production
RUN rm -r @types
RUN rm -r src
RUN rm -r tsconfig.json

ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

RUN npm install pm2 -g

EXPOSE 3000

CMD /wait && pm2-runtime /app/dist/server.js