FROM node:14.15.0

WORKDIR /app
COPY package.json ./
RUN npm install
COPY ./tsconfig.json ./
COPY ./@types ./@types
COPY src /app/src
RUN ls
RUN npm run build
RUN ls
RUN ls dist

EXPOSE 3000
CMD [ "node", "/app/dist/server.js" ]