FROM node:14.15.0

WORKDIR /app
COPY package.json ./
RUN npm install
RUN npm install pm2 -g
COPY ./tsconfig.json ./
COPY ./@types ./@types
COPY src /app/src
RUN npm run build

EXPOSE 3000
CMD [ "pm2-runtime", "/app/dist/server.js" ]
